/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.samirAtivacao.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

import com.samirAtivacao.controller.BancoController;
import com.samirAtivacao.controller.ControllerUsuario;
import com.samirAtivacao.controller.GeralController;
import com.samirAtivacao.modelo.Usuario;

/**
 *
 * @author AGU
 */
@SuppressWarnings("serial")
public class Samir extends javax.swing.JFrame {

	/**
	 * Creates new form loginTeste
	 * 
	 * @throws SQLException
	 */
	public Samir() {
		initComponents();
		
	}
	private Thread backgroundThread;
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * 
	 * @throws SQLException
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jPasswordField1 = new javax.swing.JPasswordField();
		jToggleButton1 = new javax.swing.JToggleButton();
		jToggleButton2 = new javax.swing.JToggleButton();
		jLabel3 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jTextField3 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));
		setResizable(false);
		setType(java.awt.Window.Type.POPUP);

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel1.setText("CPF");
		jLabel1.setIconTextGap(10);

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
		jLabel2.setText("SENHA");

		jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jPasswordField1ActionPerformed(evt);
			}
		});

		jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jToggleButton1.setText("SAMIR ENTER");
		jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton1ActionPerformed(evt);
			}
		});

		jToggleButton2.setBackground(new java.awt.Color(139, 139, 139));
		jToggleButton2.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
		jToggleButton2.setForeground(new java.awt.Color(228, 9, 9));
		jToggleButton2.setSelected(true);
		jToggleButton2.setText("PARAR TRIAGEM");
		jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton2ActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel3.setText("NOME COMPLETO");
		jLabel3.setIconTextGap(10);

		jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jButton2.setText("Salvar as Infomações de Login");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jTextField3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField3ActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel5.setText("Etiqueta");
		jLabel5.setIconTextGap(10);

		jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jButton1.setText("Renviar DosPrev");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		BancoController banco = new BancoController();
		Usuario usuario = banco.loginInformacoes();
		jTextField2.setText(usuario.getNome());
		jTextField1.setText(usuario.getCpf());
		jPasswordField1.setText(usuario.getSenha());
		jTextField3.setText(usuario.getEtiqueta());

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addGap(99, 99, 99).addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addComponent(jLabel3).addGap(175, 175, 175))
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 169,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 169,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(85, 85, 85).addComponent(jButton1).addGap(337, 337, 337))
										.addGroup(layout.createSequentialGroup().addGap(18, 18, 18).addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 169,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 169,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
														javax.swing.GroupLayout.PREFERRED_SIZE))
												.addContainerGap(529, Short.MAX_VALUE))))))
				.addGroup(layout.createSequentialGroup().addGap(143, 143, 143)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 279,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 279,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton2))
						.addContainerGap(562, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel3)
						.addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
				.addGap(49, 49, 49)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton1))
				.addGap(7, 7, 7)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18).addComponent(jToggleButton1).addGap(26, 26, 26).addComponent(jButton2)
				.addGap(18, 18, 18).addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap(93, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents
	  class ActionWorker implements ActionListener {
	 public void actionPerformed(ActionEvent e) {

         SwingWorker<Void, Integer> worker = new SwingWorker<Void, Integer>() {

             @Override
             protected Void doInBackground() throws Exception {
                 //aqui tudo ocorrerá em paralelo a gui
                 //desativo o botão, adiciono uma mensagem inicial
            	 jToggleButton2.setEnabled(true);

            	// worker.execute();
                 return null;
             }

      
        
     };
	 }
	  }
	private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jPasswordField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jPasswordField1ActionPerformed

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
	}// GEN-LAST:event_jTextField1ActionPerformed

	@SuppressWarnings("deprecation")
	private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton1ActionPerformed
		

	        

	            
	             SwingWorker<Void, Integer> worker = new SwingWorker<Void, Integer>() {
	             protected Void doInBackground() throws Exception {
	                 //aqui tudo ocorrerá em paralelo a gui
	                 //desativo o botão, adiciono uma mensagem inicial
	            	
	            	 
	            	
					return null;

	            	 
	                
	             }

	      
	        
	     };
	   
		Usuario usuario = new Usuario();
		usuario.setCpf(jTextField1.getText());
		usuario.setNome(jTextField2.getText());
		usuario.setSenha(jPasswordField1.getText());
		usuario.setEtiqueta(jTextField3.getText().toUpperCase());
		GeralController shazam = new GeralController();
		shazam.samir(usuario);
		Runnable task = new Runnable() {
			@Override
			public void run() {
				shazam.InserirNoFront(usuario, false);
			}
    	};
    	backgroundThread = new Thread(task);
		// Terminate the running thread if the application exits
		backgroundThread.setDaemon(true);
		// Start the thread
		backgroundThread.start();
		
	}// GEN-LAST:event_jToggleButton1ActionPerformed

	@SuppressWarnings("deprecation")
	private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton2ActionPerformed
		System.out.println("Inicio Parada");
		GeralController controller = new GeralController();
		backgroundThread.stop();
		controller.pararTriagem();
		System.out.println("Fim parada");
		
		
		
	}// GEN-LAST:event_jToggleButton2ActionPerformed

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed

	}// GEN-LAST:event_jTextField2ActionPerformed

	@SuppressWarnings("deprecation")
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		ControllerUsuario shazam = new ControllerUsuario();
		Usuario usuario = new Usuario();
		usuario.setCpf(jTextField1.getText());
		usuario.setNome(jTextField2.getText());
		usuario.setSenha(jPasswordField1.getText());
		usuario.setEtiqueta(jTextField3.getText().toUpperCase());
		shazam.excluirUsuarioController();
		JOptionPane.showMessageDialog(null, shazam.salvarUsuarioController(usuario));
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField3ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		Usuario usuario = new Usuario();
		usuario.setCpf(jTextField1.getText());
		usuario.setNome(jTextField2.getText());
		usuario.setSenha(jPasswordField1.getText());
		usuario.setEtiqueta(jTextField3.getText().toUpperCase());
		GeralController shazam = new GeralController();
		JOptionPane.showMessageDialog(null, shazam.InserirNoFront(usuario, true));
	}// GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Samir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Samir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Samir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Samir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Samir().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JToggleButton jToggleButton1;
	private javax.swing.JToggleButton jToggleButton2;
	// End of variables declaration//GEN-END:variables
}
